### ISSUE TITLE
Filter inline CSS in HTML files

### ISSUE THREAD

**Issue by ovaskevich** [avdgaag/nanoc-cachebuster#18]
Right now, CSS styles embedded in the HTML file don't get processed. The workaround I currently use is to simply run two filters on the HTML files (i.e., after they get processed by Haml/Markdown, etc.)

    filter :cache_buster, :strategy => :css
    filter :cache_buster, :strategy => :html

**Comment by avdgaag** [comment]
Let me know if any changes are needed here (preferable a pull request).
