### ISSUE TITLE
Nanoc 4 compatibility 

### ISSUE THREAD

**Issue by jimjimovich** [avdgaag/nanoc-cachebuster#23]
Is there any chance that this project could be rewritten to work with Nanoc 4?

**Comment by avdgaag** [comment]
There might be, but not by me in the foreseeable future :smile: I haven't used Nanoc or this project in a long while now, so I have neither the knowledge or incentive to do so. Then again, the code is simple enough; it should not be too hard to recreate it for Nanoc 4…
