### ISSUE TITLE
Same fingerprint is generated for *.png images

### ISSUE THREAD

**Issue by GregOnNet** [avdgaag/nanoc-cachebuster#26]
Hi,

first thanks for providing nanoc-cachebuster. We use it for quite every asset in our project.

I noticed that for every PNG image the same fingerprint is generated.
It's the following: `cb658e8dc0b`

I experienced this behavior on two different projects. That's why I think there is a problem with `nanoc-cachbuster`.

Here are two images of two different webpages:
- http://www.beta.co-it.eu/assets/images/technologies/teamcity-cb658e8dc0b.png
- https://grossweber.com/assets/images/logo-cb658e8dc0b.png

Can you help me to solve this problem?

Thanks in advance
Greg

**Comment by avdgaag** [comment]
I no longer use this project anymore, but I'd be happy to merge any pull requests if you happen to find the solution.

**Comment by agross** [comment]
The issue is that `File.read` only reads the first `n` bytes of the binary images. For example:

```ruby
file = 'some.png'

File.read(file).length
# => 5

File.size(file)
# => 9633

File.read(file)
# => "\x89PNG\n"
```

This means that only the PNG header is used for fingerprinting. Which is obviously the same for all PNGs.

I tested on Windows Ruby 2.3.0.

**Comment by avdgaag** [comment]
> This means that only the PNG header is used for fingerprinting. Which is obviously the same for all PNGs.
> 
> I tested on Windows Ruby 2.3.0.

Interesting. I have verified that this works as expected on Mac OSX. I don't have a windows machine to test this on, so I don't think I can fix it. It sounds like a Ruby bug to me. Would you care to investigate and implement a fix in a new pull request?

**Comment by agross** [comment]
Since Ruby 1.9.1 there is `IO.binread` which reads the entire file:

```ruby
IO.binread(filename).length
# => 9633
```

**Comment by agross** [comment]
Another alternative:

```
IO.read(filename).length
# => 5

IO.read(filename, mode: 'rb').length
# => 9633

File.read(filename, mode: 'rb').length
# => 9633
```

**Comment by agross** [comment]
@avdgaag The fix is already in the repository, but it seems it never was released: https://github.com/avdgaag/nanoc-cachebuster/commit/2a10aab7a586a1a8eab3a9b9b95f1981cb5dc144

**Comment by avdgaag** [comment]
Ha! I was just starting to wonder where you found the `File.read`. I'll release a new version. Thanks for investigating.
